base: !include base.yaml
run_name: 'UNetShapeNetCar'
project_name: "ShapeNetCar"

# train setting
num_epochs: 10
batch_size: 4
eval_batch_size: 1
lr: 0.0005
device: cuda:2
save_interval: 50

# model setting
mode: "train"
model: "UNet"
# model: "PINNOperatorNet"
in_channels: 4
out_channels: 1 # pressure
num_levels: 4
hidden_channels: 64
use_position_input: True

# dataset setting
data_module: "CFDSDFDataModule"
data_dir: "./data/Training/Dataset_1"           
test_data_dir: "./data/Test/Dataset_1"      
n_train: 5
n_test: 50
sdf_spatial_resolution: [64, 64, 64]
# sdf_spatial_resolution: [32, 32, 32]
# sdf_spatial_resolution: [6, 6, 6]
point_data_pos: "press on mesh points" 

# eval setting
write_to_vtk: True
out_keys: ["pressure"]
track : "Dataset_1_pressure"

